
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        name: Mypy Python 3.10
        entry: mypy
        language: python
        types: [python]
        stages: [commit]
        args: [--strict, --ignore-missing-imports, --allow-subclassing-any, --allow-untyped-calls, --python-version=3.10]
        additional_dependencies:
          - pytest
          - pydantic
          - types-PyYAML
        require_serial: true

      - id: mypy
        name: Mypy Python 3.11
        entry: mypy
        language: python
        types: [python]
        stages: [commit]
        args: [--strict, --ignore-missing-imports, --allow-subclassing-any, --allow-untyped-calls, --python-version=3.11]
        additional_dependencies:
          - pytest
          - pydantic
          - types-PyYAML
        require_serial: true

      - id: mypy
        name: Mypy Python 3.12
        entry: mypy
        language: python
        types: [python]
        stages: [commit]
        args: [--strict, --ignore-missing-imports, --allow-subclassing-any, --allow-untyped-calls, --python-version=3.12]
        additional_dependencies:
          - pytest
          - pydantic
          - types-PyYAML
        require_serial: true
  - repo: local
    hooks:
      - id: ruff-lint-isort
        name: Ruff Lint Sort Imports
        entry: poetry run ruff check --select I .
        language: system
        types: [ python ]
        stages: [ commit, push ]
      - id: ruff-lint
        name: Ruff Lint Check
        entry: poetry run ruff format --check
        language: system
        types: [ python ]
        stages: [ commit, push ]
