
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: mypy
        name: Mypy Python 3.12
        entry: mypy .
        language: system
        types: [python]
        stages: [commit]
        args: [--strict, --ignore-missing-imports, --allow-subclassing-any, --allow-untyped-calls, --python-version=3.12]
  - repo: local
    hooks:
      - id: ruff-lint-isort
        name: Ruff Lint Sort Imports
        entry: poetry run ruff check --select I .
        language: system
        types: [ python ]
        stages: [ commit, push ]
      - id: ruff-lint
        name: Ruff Lint Check
        entry: poetry run ruff format --check
        language: system
        types: [ python ]
        stages: [ commit, push ]
